#!/bin/bash

# This file is part of DOT.
#
#     DOT is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     DOT is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with DOT.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011-2013 dothub.org
#

#
#  dot_access
#
#  Created on: 2014-02-18
#      Author: Arup Raton Roy (ar3roy@uwaterloo.ca)



USER_NAME="dot"
VM_LIST=()


#Function readMapping retrieves the username of the DOT node
#and corresping host of the provisioned VMs
#Takes the mapping file name as parameter1
function readMapping {

	flag=0
	index=0	
	#reading the mapping file
	while read line
	do
	
		if [ "$flag" -eq 0 ]; then
			#Reading the user name 
			USER_NAME=$line			
			flag=$((flag+1))
			continue
		fi
	VM_LIST[$index]="$line"
	index=$((index+1))

	
	done < $1

} 


switch1_DN=0
switch2_DN=0
switch1_port=0
switch2_port=0

function readLinks {
#Finding the DOT nodes of the switches
   switch1_DN=`awk '{if($1=="'"$1"'"){print $2}}' switch_mapping`
   switch2_DN=`awk '{if($1=="'"$2"'"){print $2}}' switch_mapping`
   switch1_port=`awk '
                    {
                    if(($1=="'"$1"'" && $3=="'"$2"'")||($1=="'"$2"'"&& $3=="'"$1"'"))
                    {
                        if($1=="'"$1"'")
                            print $2;
                        else
                            print $4;
                    }    
                    }' link_mapping`

    switch2_port=`awk '
                    {
                    if(($1=="'"$1"'" && $3=="'"$2"'")||($1=="'"$2"'"&& $3=="'"$1"'"))
                    {
                        if($1=="'"$2"'")
                            print $2;
                        else
                            print $4;
                    }    
                    }' link_mapping`



}

#Reading the mapping file
readMapping mapping

proceessIDs=()
processIndex=0
connectedVM=0
while :
do 

	echo -ne "dot>"
	
	#Reading the command
	read input
		
	#Parsing the input for input and command
	command=`echo $input| cut -f1 -d' '`
	parameter1=`echo $input| cut -f2 -d' '`
    parameter2=`echo $input| cut -f3 -d' '`	
	
	case "$command" in
		("connect") 
			#Here, parameter1 is the name of the VM 
			echo "Connecting $parameter1"
			
			foundFlag=0

			#Retrieving the the VM
			for mapping in "${VM_LIST[@]}"
			do
			
				#Finding a match
				VM_NAME=`echo "$mapping"| grep $parameter1| cut -f1 -d' '`
			
				if [ "$VM_NAME" = "$parameter1" ]; then
				
					foundFlag=1
					
					#Retrieving the ip address of the host
					IP_ADDRESS=`echo "$mapping"| grep $parameter1 | cut -f2 -d' '`
		 				
					
					#Connecting the VM
                        		virt-viewer -c qemu+ssh://$USER_NAME@$IP_ADDRESS/system $parameter1 &>/dev/null &  
                        
                       			#Storing the process id
                        		processIDs[$processIndex]="$parameter1 $! active"
                        		processIndex=$((processIndex+1))
					
		            
                    connectedVM=$((connectedVM+1))

        			break
								
				fi
			done 

			#No VM is found
                        if [ "$foundFlag" -eq 0 ]; then
                                echo "$parameter1 is not running"
                        fi			
			;;

		("disconnect") 
			#Here, the parameter1 is the name of the VM
						
			#Retrieving the proeces id of the VM
			retrieveFlag=0
			for index in "${!processIDs[@]}"
			do
				status=`echo ${processIDs[$index]}| grep $parameter1| cut -f3 -d' '`
				
				
				if [ "$status" = "active" ]; then
					#Found an active VM 
					retrieveFlag=1
					echo "Disconnecting $parameter1"
					
					#retrieving the process id
					process_id=`echo ${processIDs[$index]}|  cut -f2 -d' '`
					
					#Killing the process
					kill -9 $process_id

					#Removing the VM from the list of active VMs
					unset processIDs[$index]
					
                    connectedVM=$((connectedVM-1))

					break
				fi

			done
			
			#No VM is found
			if [ "$retrieveFlag" -eq 0 ]; then
				echo "$parameter1 is not connected"
			fi
			
			;;

		("quit")
            if [ ! "$connectedVM" = 0 ]; then

			    read -r -p "Do you want to disconnect all VMs? [Y/n]" response
			    response=${response,,} # tolower
			
			    if [[ $response =~ ^(yes|y| ) ]]; then
				    for process in "${processIDs[@]}"
				    do
					    status=`echo $process| cut -f3 -d' '`
                                            VM=`echo $process| cut -f1 -d' '`        

					    if [ "$status" = "active" ]; then
						    #Found an active VM 
						    echo "Disconnecting $VM"

						    #retrieving the process id
						    process_id=`echo $process|  cut -f2 -d' '`

						    #Killing the process
						    kill -9 $process_id

                        fi

				    done
			
			    fi
            fi

		    echo "Exiting...."
			exit
			;;
        
        ("clean")
            case "$parameter1" in
                ("all")
                    read -r -p "Do you want to destroy all VMs and VSs? [Y/n]" response
                    response=${response,,} # tolower
    
                    if [[ $response =~ ^(yes|y| ) ]]; then
 
                        for machine in `cat mapping | grep h | awk '{print $2}'| sort |uniq`
                        do
                            echo "Cleaning $machine"
                            scp clean_machine.sh $USER_NAME@$machine:~  
                            ssh $USER_NAME@$machine "sudo ./clean_machine.sh"
                            ssh $USER_NAME@$machine "rm ~/clean_machine.sh"
                        
                        done
                        #Cleaning all clone images
                        rm ../resources/images/clone_*.qcow2
                        echo "$USER_NAME" > mapping
                        exit 
                    fi 
                ;;
                (*)
                    echo "To clean DOT: clean all"
            esac
            ;;
        ("attach")
                #Finding the DOT nodes of the switches
                readLinks $parameter1 $parameter2
                ssh $USER_NAME@$switch1_DN "sudo ovs-vsctl add-port topo${parameter1:1} $switch1_port"
                ssh $USER_NAME@$switch2_DN "sudo ovs-vsctl add-port topo${parameter2:1} $switch2_port"
            ;;

        ("detach")
                readLinks $parameter1 $parameter2
                ssh $USER_NAME@$switch1_DN "sudo ovs-vsctl del-port topo${parameter1:1} $switch1_port"
                ssh $USER_NAME@$switch2_DN "sudo ovs-vsctl del-port topo${parameter2:1} $switch2_port"
           ;;

        ("ping")
                echo "pinging $parameter2"
                image_id=`grep $parameter1 mapping|cut -f3 -d' '`
                image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $image_uname@$parameter1 "ping $parameter2" 
            ;;
        ("pingAll")
                hosts=(`awk '{if(NR!=1){print $1}}' mapping`)
                numberOfHosts=${#hosts[@]}
                for (( i=0; i<=$numberOfHosts-2; i++ ))
                do
                    for (( j=$i+1; j<=$numberOfHosts-1; j++ ))
                    do 
                        echo "Pinging ${hosts[$i]}->${hosts[$j]}"
                        image_id=`grep ${hosts[$i]} mapping|cut -f3 -d' '`
                        image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $image_uname@${hosts[$i]} "ping ${hosts[$j]} -c 4"
                        echo ""
                    done
                done
            ;;

         ("run")
                case "$parameter1" in
                    ("-b")
                        #Running in background
                        case "$parameter2" in
                            ("-s")
                                host=`echo $input| cut -f4 -d' '`
                                image_id=`grep $host mapping|cut -f3 -d' '`
                                image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                                scriptWithPath=`echo $input| awk '{$1="";$2="";$3="";$4="";print $0}'` 
                                scriptName=`basename $scriptWithPath`
                                scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $scriptWithPath $image_uname@$host: >/dev/null
                                ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -f -i key $image_uname@$host "./$scriptName"
                        
                            ;;
                            
                            (*)
                                host=$parameter2
                                image_id=`grep $host mapping|cut -f3 -d' '`
                                image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                                runCommand=`echo $input| awk '{$1="";$2="";$3=""; print $0}'`
                                ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -f -i key $image_uname@$host "$runCommand"
     
                            ;;
                        esac
                    ;;
                   ("-s")
                        host=$parameter2
                        image_id=`grep $host mapping|cut -f3 -d' '`
                        image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                        scriptWithPath=`echo $input| awk '{$1="";$2="";$3=""; print $0}'` 
                        scriptName=`basename $scriptWithPath`
                        echo "$scriptName"
                        scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $scriptWithPath $image_uname@$host: >/dev/null
                        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $image_uname@$host "./$scriptName"
                    ;;
                    (*)
                        host=$parameter1
                        image_id=`grep $host mapping|cut -f3 -d' '`
                        image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`
                        runCommand=`echo $input| awk '{$1="";$2=""; print $0}'`
                        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key $image_uname@$host "$runCommand"
                    ;;
                esac
            ;;

        ("monitor")
            case "$parameter1" in
                ("-c")
                    #Controller monitor
                    case "$parameter2" in
                        ("start")
                            of_version=`awk '{if(NR==1){print $1}}' ctrl_mapping`
                            ctrl=`echo $input| cut -f4 -d' '`
                            ip_ctrl=`awk '{if($1=="'"$ctrl"'") print $2}' ctrl_mapping`
                            port_ctrl=`awk '{if($1=="'"$ctrl"'") print $3}' ctrl_mapping`

                            common_filter="-f \"port $port_ctrl\" "
                            common_fields="-T fields -e frame.time -e ip.src -e ip.dst -e tcp.srcport -e tcp.dstport "
                            
                            if [ "$of_version" = "1.0" ]; then
                                of_filter="-Y \"openflow_v1\" "
                                of_fields="-e openflow_1_0.type -e openflow.datapath_id "
                            elif [ "$of_version" = "1.3" ]; then
                                of_filter="-Y \"openflow_v4\" " 
                                of_fields="-e openflow_v4.type -e openflow_v4.switch_features.datapath_id "
                         
                            fi

                            capture_command="sudo tshark "$common_filter$of_filter$common_fields$of_fields
                            #check whether it is inband controller
                            if [ ! -z "$ip_ctrl" ]; then
                            
                                monitor_file=$ctrl.`date | tr ' ' '_'`".log"
                             
                                #check in band
                                in_band=`echo $ip_ctrl| awk -F"." '{{if($1==10 && $2==254) {print "true";} else{print "false"} }}'`
                                if [ $in_band = "true" ]; then
                                    host_name="h"`echo $ip_ctrl| awk -F"." '{host_id=$3*256+$4; print host_id}'`
                                    image_id=`grep $host_name mapping|cut -f3 -d' '`
                                    image_uname=`head -$image_id image_username| tail -1|cut -f2 -d' '`

                                    options=" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key "
                                    address=" $image_uname@$host_name" 
                                    
                                    
                                    #As remote we have to ssh it
                                    echo "$capture_command&>$monitor_file& ">tempScript 
                                    echo 'echo $!' >> tempScript
                                    chmod +x tempScript
                                    
                                    scp $options tempScript $address: >/dev/null 2>&1
                                    process_id=`ssh $options$address './tempScript' 2>/dev/null`
                                    echo "$ctrl $address $((process_id+1)) $monitor_file">>ongoing_monitoring
                                    rm tempScript

                                else
                                    #assuming local controller
                                    echo "$capture_command"
                                    command_to_run="$capture_command & > ../log/$monitor_file"
                                    echo "$command_to_run"
                                    eval "($command_to_run) &"
                                    process_id=$!
                                    echo "pid: $process_id"
                                    echo "$ctrl LOCAL $((process_id+2)) $monitor_file" >> ongoing_monitoring
                                fi
                                
                                echo "Monitioring is started..."
                                echo "The output will be stored at {DOT_ROOT}/log/$monitor_file when stopped"

                            fi
                            
                        ;;
                        ("stop")
                            ctrl=`echo $input| cut -f4 -d' '`
                            options=" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i key "
                            line_num=`awk '{if($1=="'"$ctrl"'"){print NR; exit;}}' ongoing_monitoring`
                            address=`awk '{if($1=="'"$ctrl"'"){print $2; exit;}}' ongoing_monitoring`
                            pid=`awk '{if($1=="'"$ctrl"'"){print $3; exit;}}' ongoing_monitoring`
                            file=`awk '{if($1=="'"$ctrl"'"){print $4; exit;}}' ongoing_monitoring`
                            
                            if [ ! -z "$pid" ]; then 
                                mkdir ../log >/dev/null 2>&1
                                
                                if [ "$address" == "LOCAL" ]; then
                                    sudo kill -9 $pid
                                else
                                    ssh $options $address "sudo kill -9 $pid" >/dev/null 2>&1
                                    scp $options $address:$file ../log/ >/dev/null 2>&1
                                    ssh $options $address "sudo rm $file" >/dev/null 2>&1
                                fi
                                    
                                awk '{if(NR !='"$line_num"') print $0}' ongoing_monitoring > temp.om && mv temp.om ongoing_monitoring
                            fi
                        ;;
                    esac
                ;;
                ("-s")
                    #Switch monitor
                    case "$parameter2" in
                        ("start")

                        ;;

                        ("stop")

                        ;;
                    esac
                  
                ;;
            esac

            ;;
    	(*) 
			echo "For connecting to VM: connect h#"
			echo "For disconnecting a VM: disconnect h#"
            echo "For detaching a link: detach s# s#"
            echo "For reattaching a link: attach s# s#"
            echo "Ping: ping h# h#"
            echo "For sending ping between all pair of hosts: PingAll"
            echo "For running command in a host: run [-b] [-s] command/scriptfile"
            echo "For cleaning DOT: clean all"
			echo "To exit: quit"
			;;

	esac
done
