#!/bin/bash

# This file is part of DOT.
#
#     DOT is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     DOT is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with DOT.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2011-2013 dothub.org
#

#
#  dot_access
#
#  Created on: 2014-02-18
#      Author: Arup Raton Roy (ar3roy@uwaterloo.ca)

Switch1_ID=$1
Switch1_DN=$2
Switch1_port=$3
Switch2_ID=$4
Switch2_DN=$5
Switch2_port=$6
USER_NAME=$7

ssh $USER_NAME@$Switch1_DN "sudo ovs-vsctl del-port topo$Switch1_ID $Switch1_port"
ssh $USER_NAME@$Switch2_DN "sudo ovs-vsctl del-port topo$Switch2_ID $Switch2_port"
